/*
  Spaceships: Generate spaceship names. Based on the petname library by Dustin Kirkland
*/

package spaceships

import (
	"math/rand"
	"strings"
	"time"
)

var (
	cultureShips = [...]string{
		"Ablation",
		"Advanced Case Of Chronic Patheticism",
		"A Fine Disregard For Awkward Facts",
		"All The Same, I Saw It First",
		"A Momentary Lapse Of Sanity",
		"Another Fine Product From The Nonsense Factory",
		"Anticipation Of A New Lover's Arrival, The",
		"Anything Legal Considered",
		"Appeal To Reason",
		"Arbitrary",
		"Armchair Traveller",
		"Arrested Development",
		"A Series Of Unlikely Explanations",
		"A Ship With A View",
		"Attitude Adjuster",
		"Awkward Customer",
		"Bad For Business",
		"Beastly To The Animals",
		"Beats Working",
		"Big Sexy Beast",
		"Bodhisattva, OAQS",
		"Boo!",
		"Bora Horza Gobuchul",
		"Break Even",
		"But Who's Counting?",
		"Caconym",
		"Cantankerous",
		"Cargo Cult",
		"Charitable View",
		"Charming But Irrational",
		"Congenital Optimist",
		"Contents May Differ",
		"Control Surface",
		"Conventional Wisdom",
		"Credibility Problem",
		"Death And Gravity",
		"Demented But Determined",
		"Determinist",
		"Different Tan",
		"Displacement Activity",
		"Don't Try This At Home",
		"Dramatic Exit",
		"Dressed Up To Party ",
		"Eight Rounds Rapid",
		"Empiricist",
		"Eschatologist",
		"Ethics Gradient",
		"Excuses And Accusations",
		"Experiencing A Significant Gravitas Shortfall",
		"Falling Outside the Normal Moral Constraints",
		"Fate Amenable To Change",
		"Fine Till You Came Along",
		"Fixed Grin",
		"Flexible Demeanour",
		"Frank Exchange of Views",
		"Full Refund",
		"Funny, It Worked Last Time...",
		"Germane Riposte",
		"God Told Me To Do It",
		"Grey Area",
		"Gunboat Diplomat",
		"Halation Effect",
		"Hand Me The Gun And Ask Me Again",
		"Happy Idiot Talk",
		"Headcrash",
		"Heavy Messing",
		"Helpless In The Face Of Your Beauty",
		"Heresiarch",
		"Hidden Income",
		"Highpoint",
		"Honest Mistake",
		"Hylozoist",
		"I Blame My Mother",
		"I Blame The Parents",
		"I Blame Your Mother",
		"Inappropriate Response",
		"Injury Time",
		"In One Ear",
		"Irregular Apocalypse",
		"I Said, I've Got A Big Stick",
		"I Thought He Was With You",
		"It'll Be Over By Christmas",
		"It's Character Forming",
		"It's My Party And I'll Sing If I Want To",
		"Jaundiced Outlook",
		"Just Another Victim Of The Ambient Morality",
		"Just Passing Through",
		"Just Read The Instructions",
		"Just Testing",
		"Just The Washing Instruction Chip In Life's Rich Tapestry",
		"Kakistocrat",
		"Killing Time",
		"Kiss My Ass",
		"Kiss This Then",
		"Labtebricolephile",
		"Lacking That Small Match Temperament",
		"Lapsed Pacifist",
		"Lasting Damage",
		"Lasting Damage I",
		"Lasting Damage II",
		"Learned Response",
		"Lightly Seared On The Reality Grill",
		"Limiting Factor",
		"Limivorous",
		"Little Rascal",
		"Liveware Problem",
		"Long View",
		"Lucid Nonsense",
		"Me, I'm Counting",
		"Minority Report",
		"Misophist",
		"Mistake Not...",
		"Nervous Energy",
		"Never Talk To Strangers",
		"New Toy",
		"No Fixed Abode",
		"No More Mr Nice Guy",
		"No One Knows What The Dead Think",
		"Not Invented Here",
		"Not Wanted On Voyage",
		"Now Look What You've Made Me Do",
		"Now We Try It My Way",
		"Nuisance Value",
		"Of Course I Still Love You",
		"Only Slightly Bent",
		"Outstanding Contribution To The Historical Process",
		"Passing By And Thought I'd Drop In",
		"Peace Makes Plenty",
		"Pelagian",
		"Perfidy",
		"Poke It With A Stick",
		"Pressure Drop",
		"Pride Comes Before A Fall",
		"Prime Mover",
		"Problem Child",
		"Profit Margin",
		"Prosthetic Conscience",
		"Pure Big Mad Boat Man",
		"Qualifier",
		"Questionable Ethics",
		"Quietly Confident",
		"Rapid Random Response Unit",
		"Ravished By The Sheer Implausibility Of That Last Statement",
		"Reasonable Excuse",
		"Recent Convert",
		"Reformed Nice Guy",
		"Refreshingly Unconcerned With The Vulgar Exigencies Of Veracity",
		"Resistance Is Character-Forming",
		"Revisionist",
		"Sacrificial Victim",
		"Sanctioned Parts List",
		"Scar Glamour",
		"Screw Loose",
		"Seed Drill",
		"Sense Amid Madness, Wit Amidst Folly",
		"Serious Callers Only",
		"Shoot Them Later",
		"Size Isn't Everything",
		"Sleeper Service",
		"Smile Tolerantly",
		"Sober Counsel",
		"Someone Else's Problem",
		"So Much For Subtlety",
		"Space Monster",
		"Steely Glint",
		"Stranger Here Myself",
		"Subtle Shift In Emphasis",
		"Sweet and Full of Grace",
		"Synchronize Your Dogmas",
		"Tactical Grace",
		"Teething Problems",
		"Thank You And Goodnight",
		"The Ends Of Invention",
		"The Precise Nature Of The Catastrophe",
		"The Usual But Etymologically Unsatisfactory",
		"Thorough But... Unreliable",
		"Total Internal Reflection",
		"Trade Surplus",
		"Transient Atmospheric Phenomenon",
		"Ultimate Ship The Second",
		"Unacceptable Behaviour",
		"Undesirable Alien",
		"Unfortunate Conflict Of Evidence",
		"Uninvited Guest",
		"Unreliable Witness",
		"Unwitting Accomplice",
		"Use Psychology",
		"Value Judgement",
		"Very Little Gravitas Indeed",
		"Vulgarian",
		"Warm, Considering",
		"We Haven't Met But You're A Great Fan Of Mine",
		"Well I Was In The Neighbourhood",
		"What Are the Civilian Applications?",
		"What Is The Answer And Why?",
		"Wisdom Like Silence",
		"Within Reason",
		"Xenocrat",
		"Xenoglossicist",
		"Xenophobe",
		"Yawning Angel",
		"You Call This Clean?",
		"You'll Clean That Up Before You Leave",
		"You'll Thank Me Later",
		"You May Not Be The Coolest Person Here",
		"You Naughty Monsters",
		"Youthful Indiscretion",
		"You Would If You Really Loved Me",
		"Zealot",
		"Zero Credibility",
		"Zero Gravitas",
		"Zoologist",
	}
)

func NonDeterministicMode() {
	rand.Seed(time.Now().UnixNano())
}

func CultureShip() string {
	return cultureShips[rand.Intn(len(cultureShips))]
}

func Generate(separator string) string {
	cultureShip := CultureShip()
	// Split the culture ship name by space
	words := strings.Split(cultureShip, " ")
	// Join the words with the separator
	return strings.Join(words, separator)
}
